package com.goormgb.be.global.environment;

import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

import com.goormgb.be.global.exception.ErrorCode;

/**
 * 운영 환경용 에러 응답 전략 (staging, prod).
 *
 * <p>ErrorCode를 HTTP 상태 시리즈(CLIENT_ERROR, SERVER_ERROR)로 추상화하여
 * 내부 에러 코드가 외부에 노출되지 않도록 한다.</p>
 *
 * <p>응답 예시:</p>
 * <pre>
 * {
 *   "code": "CLIENT_ERROR",
 *   "message": "온보딩 선호도 정보를 찾을 수 없습니다."
 * }
 * </pre>
 *
 * <p>추후 에러 코드 추상화 작업 시 이 클래스를 확장하여
 * 특정 ErrorCode에 대해 커스텀 코드를 반환하도록 구현할 수 있다.</p>
 *
 * @see ErrorResponseStrategy
 * @see DetailedErrorResponseStrategy
 */
@Component
@Profile({"staging", "prod"})
public class AbstractErrorResponseStrategy implements ErrorResponseStrategy {

	@Override
	public String resolveCode(ErrorCode errorCode) {
		return switch (errorCode) {
			// Seat Hold (SEAT_HOLD_OWNERSHIP_DENIED 제외 — 권한 에러는 추상화 유지)
			case INVALID_SEAT_HOLD_REQUEST, MATCH_SEAT_NOT_FOUND,
				 SEAT_ALREADY_HELD_BY_OTHER, SEAT_ALREADY_SOLD,
				 SEAT_HOLD_NOT_FOUND, SEAT_HOLD_EXPIRED,
				 PRICE_POLICY_NOT_FOUND, SEAT_SESSION_NOT_FOUND,

				 // Seat Assignment
				 NO_CONSECUTIVE_SEAT_AVAILABLE, SEAT_LOCK_ACQUISITION_FAILED,

				 // Order
				 INVALID_ORDER_STATUS, ORDER_SEAT_EMPTY, ORDER_TOTAL_PRICE_MISMATCH,
				 EXCEEDED_MAX_TICKETS_PER_ORDER, ORDER_NOT_FOUND,

				 // Queue / PreQueue
				 QUEUE_ALREADY_ENTERED, QUEUE_ENTRY_NOT_FOUND, ADMISSION_TOKEN_EXPIRED,
				 PREQUEUE_OPTIONS_REQUIRED, PREQUEUE_MARKER_SYNC_FAILED,
				 INVALID_TICKET_COUNT, INVALID_BOOKING_OPTIONS -> errorCode.name();

			default -> errorCode.getStatus().series().name();
		};
	}

	@Override
	public String resolveMessage(ErrorCode errorCode) {
		return switch (errorCode) {
			case INVALID_TOKEN, EXPIRED_TOKEN, INVALID_CREDENTIALS,
				 REFRESH_TOKEN_NOT_FOUND, REFRESH_TOKEN_MISMATCH,
				 INVALID_TOKEN_TYPE, BLACKLISTED_TOKEN, INVALID_INTERNAL_API_KEY,
				 OAUTH_TOKEN_REQUEST_FAILED, OAUTH_CODE_REQUEST_FAILED,
				 OAUTH_CODE_EXPIRED, OAUTH_REDIRECT_URI_MISMATCH,
				 UNAUTHORIZED -> "인증 정보가 유효하지 않습니다.";

			case FORBIDDEN, USER_DEACTIVATED, ORDER_ACCESS_DENIED,
				 SEAT_HOLD_OWNERSHIP_DENIED, INQUIRY_ACCESS_DENIED -> "접근 권한이 없습니다.";

			case INTERNAL_SERVER_ERROR, OAUTH_PROVIDER_ERROR -> "서버 통신에 일시적 오류가 발생했습니다.";

			case QUEUE_ALREADY_ENTERED, ADMISSION_TOKEN_EXPIRED, MATCH_NOT_AVAILABLE_FOR_QUEUE,
				 PREQUEUE_OPTIONS_REQUIRED, PREQUEUE_MARKER_SYNC_FAILED,
				 NO_AVAILABLE_BLOCK, NO_CONSECUTIVE_SEAT_AVAILABLE, SEAT_LOCK_ACQUISITION_FAILED,
				 SEAT_ALREADY_HELD_BY_OTHER, SEAT_ALREADY_SOLD, SEAT_HOLD_EXPIRED,
				 PAYMENT_ALREADY_COMPLETED, CASH_RECEIPT_ALREADY_EXISTS,
				 INVALID_PAYMENT_METHOD, INVALID_SEAT_HOLD_REQUEST,
				 BANK_TRANSFER_NOT_AVAILABLE,
				 INVALID_TICKET_COUNT, INVALID_BOOKING_OPTIONS,
				 INVALID_PAGE_SIZE, INVALID_TICKET_TAB,
				 TICKET_CANCEL_NOT_ALLOWED, ENTRY_QR_NOT_AVAILABLE_YET, ENTRY_QR_MATCH_STARTED,
				 INVALID_INQUIRY_CATEGORY, INQUIRY_NOT_FOUND,
				 INQUIRY_FILE_TYPE_NOT_ALLOWED, INQUIRY_FILE_SIGNATURE_MISMATCH,
				 INQUIRY_FILE_TOO_LARGE, INQUIRY_FILE_KEY_INVALID, INQUIRY_FILE_NOT_FOUND,
				 INVALID_MATCH_MONTH, INVALID_MATCH_YEAR,
				 INVALID_PROMOTE_COUNT, QUEUE_PROMOTION_NOT_ALLOWED,
				 INVALID_ORDER_STATUS, ORDER_SEAT_EMPTY,
				 PRICE_POLICY_NOT_FOUND, SEAT_SESSION_NOT_FOUND,

				 ONBOARDING_NOT_COMPLETED, ONBOARDING_ALREADY_COMPLETED,
				 INVALID_PREFERENCE_RANK, DUPLICATE_PREFERENCE_VIEWPOINT,
				 DUPLICATE_PREFERENCE_SEAT_HEIGHT, DUPLICATE_PREFERENCE_SECTION,
				 INVALID_PREFERENCE_PRIORITY_VALUE, INVALID_PRICE_RANGE,
				 MISSING_REQUIRED_PREFERENCE_FIELD, PREFERENCE_NOT_FOUND_FOR_UPDATE,
				 INVALID_MARKETING_CONSENT, INVALID_VIEWPOINT_PRIORITY_COUNT,
				 INVALID_VIEWPOINT_PRIORITY_SEQUENCE, INVALID_PREFERRED_BLOCK_COUNT,
				 DUPLICATE_PREFERRED_BLOCK,

				 MATCH_NOT_FOUND, CLUB_NOT_FOUND, SECTION_NOT_FOUND, BLOCK_NOT_FOUND,
				 PREFERENCE_NOT_FOUND, ORDER_NOT_FOUND, PAYMENT_NOT_FOUND,
				 MATCH_SEAT_NOT_FOUND, SEAT_HOLD_NOT_FOUND, QUEUE_ENTRY_NOT_FOUND,

				 USER_ALREADY_EXISTS, USER_ALREADY_BLOCKED, USER_ALREADY_ACTIVE,
				 USER_NOT_FOUND, EXCEEDED_MAX_TICKETS_PER_ORDER, ORDER_TOTAL_PRICE_MISMATCH -> errorCode.getMessage();

			default -> switch (errorCode.getStatus().series()) {
				case SERVER_ERROR -> "서버 통신에 일시적 오류가 발생했습니다.";
				default -> "요청을 처리할 수 없습니다.";
			};
		};
	}

	@Override
	public String resolveMessage(String detailedMessage, HttpStatus status) {
		return switch (status) {
			case UNAUTHORIZED -> "인증 정보가 유효하지 않습니다.";
			case FORBIDDEN -> "접근 권한이 없습니다.";
			case INTERNAL_SERVER_ERROR, BAD_GATEWAY -> "서버 통신에 일시적 오류가 발생했습니다.";
			default -> "요청을 처리할 수 없습니다.";
		};
	}
}
