server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOriginPatterns:
                  - "${ALLOWED_ORIGINS}"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
          routes:
            - id: auth-guard
              uri: ${AUTH_GUARD_URL}
              predicates:
                - Path=/auth/**
            - id: queue
              uri: ${QUEUE_URL}
              predicates:
                - Path=/queue/**
            - id: seat
              uri: ${SEAT_URL}
              predicates:
                - Path=/seat/**
            - id: order-core
              uri: ${ORDER_CORE_URL}
              predicates:
                - Path=/order/**

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth-Guard
        url: /auth/v3/api-docs
      - name: Queue
        url: /queue/v3/api-docs
      - name: Seat
        url: /seat/v3/api-docs
      - name: Order-Core
        url: /order/v3/api-docs
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    com.goormgb.be: DEBUG
    org.springframework.web: DEBUG
