server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: auth-guard
              uri: ${AUTH_GUARD_URL}
              predicates:
                - Path=/auth/**
            - id: queue
              uri: ${QUEUE_URL}
              predicates:
                - Path=/queue/**
            - id: seat
              uri: ${SEAT_URL}
              predicates:
                - Path=/seat/**
            - id: order-core
              uri: ${ORDER_CORE_URL}
              predicates:
                - Path=/order/**
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  public-key: ${JWT_PUBLIC_KEY}
  issuer: ${JWT_ISSUER}
  access-token:
    audience: ${JWT_ACCESS_TOKEN_AUDIENCE}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web: DEBUG
