server:
  port: 8085

spring:
  application:
    name: api-gateway
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  access-token:
    audience: ${JWT_ACCESS_TOKEN_AUDIENCE}
