server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "${ALLOWED_ORIGINS}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.goormgb.be: DEBUG
