server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-guard
  jackson:
    time-zone: UTC
    data-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time-zone: UTC

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  issuer: ${JWT_ISSUER}
  access-token:
    audience: ${JWT_ACCESS_TOKEN_AUDIENCE}
    expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    audience: ${JWT_REFRESH_TOKEN_AUDIENCE}
    expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION}
  cookie:
    secure: false

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

  auth-url: https://kauth.kakao.com/oauth/authorize
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, db
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  config: classpath:logback-spring.xml
