server:
  port: 8080
  servlet:
    context-path: /auth
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100

spring:
  application:
    name: auth-guard
  jackson:
    time-zone: UTC
    data-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 100

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time-zone: UTC

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER}
      acks: ${KAFKA_PRODUCER_ACKS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  issuer: ${JWT_ISSUER}
  access-token:
    audience: ${JWT_ACCESS_TOKEN_AUDIENCE}
    expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    audience: ${JWT_REFRESH_TOKEN_AUDIENCE}
    expiration-hours: ${JWT_REFRESH_TOKEN_EXPIRATION}
  load-test:
    token-expiration-minutes: ${JWT_LOADTEST_TOKEN_EXPIRATION:15}
  cookie:
    secure: false

internal:
  api-key: ${INTERNAL_API_KEY}

encryption:
  db-key: ${DB_ENCRYPTION_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  allowed-redirect-uris:
    - https://playball.one
    - https://staging.playball.one

  auth-url: https://kauth.kakao.com/oauth/authorize
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          include: readinessState, db
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  config: classpath:logback-spring.xml
